### PR TITLE
SPARK-133: Add detection for MapType

### PR DESCRIPTION
**Pull request by jniebuhr**
As described in the Jira Issue https://jira.mongodb.org/browse/SPARK-133 I have added detection for MapTypes when a Struct grows over 250 keys. This should help people who use maps in their MongoDB documents.

### CODE REVIEW

**Comment by rozza** [comment]
At an initial glance it looks ok but it's missing any tests, could you add a test case for it?

**Comment by jniebuhr** [comment]
yes, I will

**Comment by jniebuhr** [comment]
I've added a test case for map detection. It tests both too few keys and conflicting value types and of course the success cases.

**Comment by jniebuhr** [comment]
Would it be possible to also backport this to 2.1? We can't upgrade our Spark to 2.2 just yet.

**Comment by kervin521** [comment]
Whether support to query muti collection?

e.g. collection:
collectiontest,collectiontest_201701,collectiontest_201702,collectiontest_201703,collectiontest_201704,.....

how to get data of all collection include startwith "collectiontest"?

**Comment by jniebuhr** [comment]
@kervin521 that has nothing to do with this pull request

**Comment by jniebuhr** [comment]
@rozza Any news on this?

**Comment by rozza** [comment]
@jniebuhr the PR looks good and will be merged for the next release. I'll look to include in the 2.1 release as well.

**Comment by kervin521** [comment]
com.MongoDB.MongoCursorNotFoundException: 
 Query failed with error code -5 and error message 'Cursor 85789014536 not found on server ****:*' on server *：*

**Comment by wangqingyi2013** [comment]
how to solve it?
error:
com.mongodb.MongoCommandException: Command failed with error 13: 'not authorized on admin to execute command { collStats: "route" }' on server xxx.xxx.xx.xx:8636. The full response is { "ok" : 0.0, "errmsg" : "not authorized on admin to execute command { collStats: "route" }", "code" : 13 }

**Comment by jniebuhr** [comment]
We've had some mongo spark releases but this still doesn't seem to be merged. Is there something holding back this PR?

**Comment by rozza** [comment]
Hi @jniebuhr, apologies this is still definitely on the radar for the next major release. I'm undecided if it is best to have it enabled via an option / have the key count configurable.

The recent releases of the connector focused on ensuring the connector worked as expected with different (newer) versions of Spark.

**Comment by jniebuhr** [comment]
@rozza Yes, making it configurable is probably a good idea, I'll update the PR

**Comment by jniebuhr** [comment]
@rozza I've updated the PR, an enabled option and the minimum keys option is now configurable through both Spark Config and ReadConfig. I've had to push the ReadConfig through quite some methods, I hope you don't mind.

**Comment by rozza** [comment]
Rebased and merged in b62783 - Many thanks @jniebuhr for the PR.

**Pull request closed without merging**
